name = "cs2-webradar-relay"
main = "worker.js"
compatibility_date = "2024-05-01"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[placement]
mode = "smart"

[vars]
# Comma-separated list of allowed viewer origins (e.g., your Pages URL)
# Example: "https://radar.lucrepostando.online,https://yourapp.pages.dev"
ALLOWED_ORIGINS = "https://radar.lucrepostando.online,https://cs2map-webapp.pages.dev"
